import * as XLSX from "xlsx";
import { CM_BASIC_FIELDS, CM_LEGAL_FIELDS, CM_ADDRESS_FIELDS, getNextCompanyCode } from "../../modules/company-master/data/companyMasterFields";

// List of all fields with their key, label, and whether required
export const ALL_FIELDS_CONFIG = [
  ...CM_BASIC_FIELDS,
  ...CM_LEGAL_FIELDS,
  ...CM_ADDRESS_FIELDS,
  { key: "status", label: "Status" },
];

const REQUIRED_KEYS = ["companyName", "panNo", "gstin", "registeredOffice", "country", "state", "city"];

// Map header string (e.g. "Company Code", "Company Name * (Required)") to canonical field key
function normalizeHeader(h) {
  return String(h || "")
    .toLowerCase()
    .replace(/required|optional|auto-generated|autogenerated/g, "")
    .replace(/[^a-z0-9]/g, "");
}

const HEADER_MAP = {};
ALL_FIELDS_CONFIG.forEach((f) => {
  HEADER_MAP[normalizeHeader(f.key)] = f.key;
  HEADER_MAP[normalizeHeader(f.label)] = f.key;
});
// Additional alias mappings for common variations
HEADER_MAP["panno"] = "panNo";
HEADER_MAP["pan"] = "panNo";
HEADER_MAP["cinllpin"] = "cinLlpin";
HEADER_MAP["cin"] = "cinLlpin";
HEADER_MAP["importexportcodeiec"] = "iec";
HEADER_MAP["pincode"] = "pinCode";
HEADER_MAP["zip"] = "pinCode";
HEADER_MAP["zipcode"] = "pinCode";
HEADER_MAP["registeredoffice"] = "registeredOffice";
HEADER_MAP["factoryaddress"] = "factoryAddress";
HEADER_MAP["branchaddress"] = "branchAddress";
HEADER_MAP["businesstype"] = "businessType";
HEADER_MAP["companycode"] = "companyCode";
HEADER_MAP["companyname"] = "companyName";
HEADER_MAP["legalname"] = "legalName";
HEADER_MAP["shortname"] = "shortName";

// Helper to normalize field values for duplicate checking
const norm = (v) => (v === null || v === undefined ? "" : String(v).trim());

const ALL_RECORD_FIELDS = ALL_FIELDS_CONFIG.map((f) => f.key);

function isExactDuplicate(rec1, rec2) {
  return ALL_RECORD_FIELDS.every((k) => norm(rec1[k]) === norm(rec2[k]));
}

// Generate & download comprehensive sample Excel template file with * (Required) field markers
export function downloadSampleExcel() {
  const sampleData = [
    {
      "Company Code (Auto-Generated if blank)": "CMP-001",
      "Company Name * (Required)": "Silver Muller Seals LLP",
      "Legal Name (Optional)": "Silver Muller Seals LLP",
      "Short Name (Optional)": "SMS",
      "Business Type (Optional)": "Manufacturing",
      "Industry (Optional)": "Rubber/Oil Seal Manufacturing",
      "PAN No. * (Required - 10 chars e.g. ABCDE1234F)": "ABCDE1234F",
      "GSTIN * (Required - 15 chars e.g. 27ABCDE1234F1Z5)": "27ABCDE1234F1Z5",
      "CIN / LLPIN (Optional)": "AAA-1234",
      "TAN (Optional)": "MUM12345A",
      "MSME Registration (Optional)": "UDYAM-MH-01-0012345",
      "Factory License No. (Optional)": "FAC-98765",
      "Import Export Code (IEC) (Optional)": "0123456789",
      "PF Establishment Code (Optional)": "MH/BAN/0012345/000",
      "ESI Code (Optional)": "31000123450000101",
      "Professional Tax No. (Optional)": "27000000000P",
      "Pollution Certificate No. (Optional)": "PCB-2025-001",
      "Registered Office * (Required)": "Plot 12, Industrial Area, Sector 5",
      "Factory Address (Optional)": "Plot 12-14, Industrial Area, Sector 5",
      "Branch Address (Optional)": "",
      "Country * (Required - India or Other)": "India",
      "State * (Required - Indian State name or Province)": "Maharashtra",
      "City * (Required)": "Mumbai",
      "PIN Code (Optional)": "400001",
      "Status (Active / Inactive)": "Active",
    },
    {
      "Company Code (Auto-Generated if blank)": "CMP-002",
      "Company Name * (Required)": "Apex Engineering Solutions",
      "Legal Name (Optional)": "Apex Engineering Solutions Pvt Ltd",
      "Short Name (Optional)": "AES",
      "Business Type (Optional)": "Manufacturing",
      "Industry (Optional)": "Precision Components",
      "PAN No. * (Required - 10 chars e.g. ABCDE1234F)": "FGHIJ5678K",
      "GSTIN * (Required - 15 chars e.g. 27ABCDE1234F1Z5)": "24FGHIJ5678K1Z2",
      "CIN / LLPIN (Optional)": "U29100GJ2020PTC112233",
      "TAN (Optional)": "AHM56789B",
      "MSME Registration (Optional)": "UDYAM-GJ-02-0054321",
      "Factory License No. (Optional)": "FAC-44321",
      "Import Export Code (IEC) (Optional)": "9876543210",
      "PF Establishment Code (Optional)": "GJ/AHM/0054321/000",
      "ESI Code (Optional)": "32000543210000202",
      "Professional Tax No. (Optional)": "24000000000P",
      "Pollution Certificate No. (Optional)": "PCB-2025-002",
      "Registered Office * (Required)": "GIDC Estate, Phase II",
      "Factory Address (Optional)": "GIDC Estate, Phase II",
      "Branch Address (Optional)": "",
      "Country * (Required - India or Other)": "India",
      "State * (Required - Indian State name or Province)": "Gujarat",
      "City * (Required)": "Ahmedabad",
      "PIN Code (Optional)": "380001",
      "Status (Active / Inactive)": "Active",
    },
  ];

  const guidelinesData = [
    { "Field Name": "Company Code", "Required Status": "AUTO-GENERATED", "Format & Constraint Guidelines": "Auto-assigned in CMP-001 format if left blank." },
    { "Field Name": "Company Name", "Required Status": "REQUIRED *", "Format & Constraint Guidelines": "Mandatory. Full official company name." },
    { "Field Name": "PAN No.", "Required Status": "REQUIRED *", "Format & Constraint Guidelines": "Mandatory. Must be 10 characters (e.g. ABCDE1234F)." },
    { "Field Name": "GSTIN", "Required Status": "REQUIRED *", "Format & Constraint Guidelines": "Mandatory. Must be 15 characters (e.g. 27ABCDE1234F1Z5)." },
    { "Field Name": "Registered Office", "Required Status": "REQUIRED *", "Format & Constraint Guidelines": "Mandatory. Full registered office address." },
    { "Field Name": "Country", "Required Status": "REQUIRED *", "Format & Constraint Guidelines": "Mandatory. 'India' or custom country name (e.g. 'United States')." },
    { "Field Name": "State", "Required Status": "REQUIRED *", "Format & Constraint Guidelines": "Mandatory. Valid Indian state if Country=India, or any State/Province if Country=Other." },
    { "Field Name": "City", "Required Status": "REQUIRED *", "Format & Constraint Guidelines": "Mandatory. City name." },
    { "Field Name": "Legal Name", "Required Status": "OPTIONAL", "Format & Constraint Guidelines": "Optional." },
    { "Field Name": "Short Name", "Required Status": "OPTIONAL", "Format & Constraint Guidelines": "Optional." },
    { "Field Name": "Business Type", "Required Status": "OPTIONAL", "Format & Constraint Guidelines": "Optional. Defaults to 'Manufacturing' if empty." },
    { "Field Name": "Industry", "Required Status": "OPTIONAL", "Format & Constraint Guidelines": "Optional." },
    { "Field Name": "CIN / LLPIN", "Required Status": "OPTIONAL", "Format & Constraint Guidelines": "Optional." },
    { "Field Name": "TAN", "Required Status": "OPTIONAL", "Format & Constraint Guidelines": "Optional." },
    { "Field Name": "MSME Registration", "Required Status": "OPTIONAL", "Format & Constraint Guidelines": "Optional." },
    { "Field Name": "Factory License No.", "Required Status": "OPTIONAL", "Format & Constraint Guidelines": "Optional." },
    { "Field Name": "Import Export Code (IEC)", "Required Status": "OPTIONAL", "Format & Constraint Guidelines": "Optional." },
    { "Field Name": "PF Establishment Code", "Required Status": "OPTIONAL", "Format & Constraint Guidelines": "Optional." },
    { "Field Name": "ESI Code", "Required Status": "OPTIONAL", "Format & Constraint Guidelines": "Optional." },
    { "Field Name": "Professional Tax No.", "Required Status": "OPTIONAL", "Format & Constraint Guidelines": "Optional." },
    { "Field Name": "Pollution Certificate No.", "Required Status": "OPTIONAL", "Format & Constraint Guidelines": "Optional." },
    { "Field Name": "Factory Address", "Required Status": "OPTIONAL", "Format & Constraint Guidelines": "Optional." },
    { "Field Name": "Branch Address", "Required Status": "OPTIONAL", "Format & Constraint Guidelines": "Optional." },
    { "Field Name": "PIN Code", "Required Status": "OPTIONAL", "Format & Constraint Guidelines": "Optional 6-digit PIN code." },
    { "Field Name": "Status", "Required Status": "OPTIONAL", "Format & Constraint Guidelines": "Optional. 'Active' or 'Inactive'." },
  ];

  const workbook = XLSX.utils.book_new();

  // Sheet 1: Template Data
  const worksheet1 = XLSX.utils.json_to_sheet(sampleData);
  const colWidths1 = Object.keys(sampleData[0]).map((key) => ({
    wch: Math.max(key.length + 2, 18),
  }));
  worksheet1["!cols"] = colWidths1;
  XLSX.utils.book_append_sheet(workbook, worksheet1, "Company Master Template");

  // Sheet 2: Guidelines & Requirements
  const worksheet2 = XLSX.utils.json_to_sheet(guidelinesData);
  worksheet2["!cols"] = [{ wch: 25 }, { wch: 18 }, { wch: 60 }];
  XLSX.utils.book_append_sheet(workbook, worksheet2, "Field Requirements Guide");

  XLSX.writeFile(workbook, "company_master_template_with_required_fields.xlsx");
}

// Parse Excel file, validate header & fields & duplicates against constraints
export function parseAndValidateExcel(file, existingRecords = []) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();

    reader.onload = (e) => {
      try {
        const data = new Uint8Array(e.target.result);
        const workbook = XLSX.read(data, { type: "array" });

        const firstSheetName = workbook.SheetNames[0];
        if (!firstSheetName) {
          return resolve({ valid: false, errors: ["Excel file contains no sheets."], records: [] });
        }

        const worksheet = workbook.Sheets[firstSheetName];
        const rawJson = XLSX.utils.sheet_to_json(worksheet, { header: 1, defval: "" });

        if (rawJson.length === 0) {
          return resolve({ valid: false, errors: ["Excel sheet is completely empty."], records: [] });
        }

        // Header row (Row 1)
        const headerRow = rawJson[0].map((h) => String(h).trim());
        const fieldMapping = {}; // colIndex -> canonical key

        headerRow.forEach((colName, idx) => {
          const normH = normalizeHeader(colName);
          if (HEADER_MAP[normH]) {
            fieldMapping[idx] = HEADER_MAP[normH];
          }
        });

        // Verify all REQUIRED columns are present in the Excel header
        const mappedKeys = new Set(Object.values(fieldMapping));
        const missingRequiredColumns = [];
        REQUIRED_KEYS.forEach((reqKey) => {
          if (!mappedKeys.has(reqKey)) {
            const config = ALL_FIELDS_CONFIG.find((f) => f.key === reqKey);
            missingRequiredColumns.push(config ? config.label : reqKey);
          }
        });

        if (missingRequiredColumns.length > 0) {
          return resolve({
            valid: false,
            errors: [
              `Missing required column(s) in Excel header: ${missingRequiredColumns.join(", ")}. Please include all required columns.`,
            ],
            records: [],
          });
        }

        const dataRows = rawJson.slice(1);
        if (dataRows.length === 0) {
          return resolve({ valid: false, errors: ["Excel sheet has headers but no data rows."], records: [] });
        }

        const parsedRecords = [];
        const errors = [];

        // Valid state list for state checking
        const stateConfig = ALL_FIELDS_CONFIG.find((f) => f.key === "state");
        const validStates = new Set((stateConfig?.options || []).map((s) => s.toLowerCase()));

        // Process and validate each data row
        dataRows.forEach((row, rowIdx) => {
          const rowNumber = rowIdx + 2; // Row 1 is header, data starts at Row 2

          // Check if row is completely blank
          const isBlankRow = row.every((cell) => cell === null || cell === undefined || String(cell).trim() === "");
          if (isBlankRow) return;

          const rec = { status: "Active", logo: "" };
          ALL_FIELDS_CONFIG.forEach((f) => {
            if (f.key !== "status" && f.key !== "logo") rec[f.key] = "";
          });

          // Populate mapped cells
          Object.keys(fieldMapping).forEach((colIdx) => {
            const key = fieldMapping[colIdx];
            const cellVal = row[colIdx];
            rec[key] = cellVal !== null && cellVal !== undefined ? String(cellVal).trim() : "";
          });

          // Standardize businessType default if empty
          if (!rec.businessType) rec.businessType = "Manufacturing";
          if (!rec.status) rec.status = "Active";

          // 1. Company Code (Auto-assigned if missing/empty)
          if (!rec.companyCode || !rec.companyCode.trim()) {
            rec.companyCode = getNextCompanyCode(existingRecords.concat(parsedRecords));
          }

          // Field validations per row
          const rowErrors = [];

          // 2. Company Name
          if (!rec.companyName) {
            rowErrors.push("Company Name is required");
          }

          // 3. PAN No.
          if (!rec.panNo) {
            rowErrors.push("PAN No. is required");
          } else if (!/^[A-Za-z]{5}[0-9]{4}[A-Za-z]{1}$/.test(rec.panNo)) {
            rowErrors.push(`PAN No. '${rec.panNo}' is invalid (must be 10 characters e.g. ABCDE1234F)`);
          }

          // 4. GSTIN
          if (!rec.gstin) {
            rowErrors.push("GSTIN is required");
          } else if (rec.gstin.length !== 15 || /^0+$/.test(rec.gstin)) {
            rowErrors.push(`GSTIN '${rec.gstin}' is invalid (must be 15 characters)`);
          }

          // 5. Registered Office
          if (!rec.registeredOffice) {
            rowErrors.push("Registered Office is required");
          }

          // 6. Country
          if (!rec.country) {
            rowErrors.push("Country is required");
          }

          // 7. City
          if (!rec.city) {
            rowErrors.push("City is required");
          }

          // 8. State
          if (!rec.state) {
            rowErrors.push("State / Province is required");
          } else if (rec.country.toLowerCase() === "india" && !validStates.has(rec.state.toLowerCase())) {
            rowErrors.push(`State '${rec.state}' is not a recognized Indian state/union territory`);
          }

          // 9. PIN / ZIP Code (6-digit check for India, flexible for international)
          if (rec.pinCode && rec.pinCode.trim()) {
            const isIndia = (rec.country || "").toLowerCase() === "india";
            if (isIndia && !/^[1-9][0-9]{5}$/.test(rec.pinCode.trim())) {
              rowErrors.push(`PIN Code '${rec.pinCode}' must be a valid 6-digit PIN for India`);
            }
          }

          if (rowErrors.length > 0) {
            errors.push(`Row ${rowNumber}: ${rowErrors.join("; ")}`);
          } else {
            parsedRecords.push({ ...rec, _excelRowNumber: rowNumber });
          }
        });

        if (errors.length > 0) {
          return resolve({ valid: false, errors, records: [] });
        }

        // Duplicate validations:
        // A) Check inside the uploaded Excel sheet for duplicate rows
        for (let i = 0; i < parsedRecords.length; i++) {
          for (let j = i + 1; j < parsedRecords.length; j++) {
            if (isExactDuplicate(parsedRecords[i], parsedRecords[j])) {
              errors.push(
                `Duplicate in Excel file: Row ${parsedRecords[i]._excelRowNumber} and Row ${parsedRecords[j]._excelRowNumber} have identical company details.`
              );
            }
          }
        }

        // B) Check against existing records in database / system
        parsedRecords.forEach((newRec) => {
          const match = existingRecords.find((existRec) => isExactDuplicate(existRec, newRec));
          if (match) {
            errors.push(
              `Row ${newRec._excelRowNumber} (${newRec.companyName} - ${newRec.companyCode}): Exactly identical record already exists in the system.`
            );
          }
        });

        if (errors.length > 0) {
          return resolve({ valid: false, errors, records: [] });
        }

        // Strip metadata helper key before returning
        const finalRecords = parsedRecords.map(({ _excelRowNumber, ...rest }) => rest);
        resolve({ valid: true, errors: [], records: finalRecords });
      } catch (err) {
        resolve({ valid: false, errors: [`Failed to parse Excel file: ${err.message}`], records: [] });
      }
    };

    reader.onerror = () => {
      resolve({ valid: false, errors: ["Failed to read file from disk."], records: [] });
    };

    reader.readAsArrayBuffer(file);
  });
}

// Export any array of company records to an .xlsx file download
export function exportRecordsToExcel(recordsList, filename = "Company_Master_Records.xlsx") {
  if (!recordsList || recordsList.length === 0) return;

  const formattedRows = recordsList.map((r) => {
    const row = {};
    ALL_FIELDS_CONFIG.forEach((f) => {
      row[f.label] = r[f.key] || "";
    });
    return row;
  });

  const worksheet = XLSX.utils.json_to_sheet(formattedRows);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Company Records");

  const colWidths = Object.keys(formattedRows[0]).map((key) => ({
    wch: Math.max(key.length + 3, 16),
  }));
  worksheet["!cols"] = colWidths;

  XLSX.writeFile(workbook, filename);
}

