import * as XLSX from "xlsx";

// Canonical field keys for inventory transactions
export const INVENTORY_EXCEL_FIELDS = [
  { key: "slipNumber", label: "Slip No.", required: false, desc: "Optional manual slip reference" },
  { key: "type", label: "Type", required: true, desc: "Mandatory (ISSUE, RECEIPT, or REVERSE)" },
  { key: "fromDept", label: "From Dept", required: true, desc: "Mandatory (e.g. Stores, Production)" },
  { key: "toDept", label: "To Dept", required: false, desc: "Optional / Destination department" },
  { key: "itemCode", label: "Item Code", required: true, desc: "Mandatory (e.g. MAT-001, MAT-002)" },
  { key: "description", label: "Description", required: false, desc: "Item description (auto-filled if empty)" },
  { key: "category", label: "Category", required: false, desc: "Item category (auto-filled from master if empty)" },
  { key: "quantity", label: "Quantity", required: true, desc: "Mandatory positive quantity (> 0)" },
  { key: "timestamp", label: "Timestamp", required: false, desc: "Optional date/time (defaults to now)" },
  { key: "remarks", label: "Remarks", required: false, desc: "Optional notes" },
];

// Core mandatory columns in Excel header
const REQUIRED_HEADERS = ["type", "fromDept", "itemCode", "quantity"];

// Normalize header text for flexible matching:
// 1. Removes text in parentheses (e.g. "(Required: ISSUE / RECEIPT / REVERSE)", "(Optional)")
// 2. Removes asterisks, punctuation, spaces, and lowers case
function normalizeHeader(h) {
  return String(h || "")
    .replace(/\([^)]*\)/g, "") // Strip anything inside parentheses
    .replace(/required|optional|auto-generated|autogenerated/gi, "")
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "");
}

const HEADER_MAP = {
  "type": "type",
  "transactiontype": "type",
  "typeoftransaction": "type",
  "fromdept": "fromDept",
  "fromdepartment": "fromDept",
  "source": "fromDept",
  "sourcedept": "fromDept",
  "todept": "toDept",
  "todepartment": "toDept",
  "destination": "toDept",
  "destdept": "toDept",
  "itemcode": "itemCode",
  "item": "itemCode",
  "code": "itemCode",
  "materialcode": "itemCode",
  "category": "category",
  "categoryofitem": "category",
  "itemcategory": "category",
  "quantity": "quantity",
  "qty": "quantity",
  "amount": "quantity",
  "slipno": "slipNumber",
  "slipnumber": "slipNumber",
  "slip": "slipNumber",
  "manualslipno": "slipNumber",
  "description": "description",
  "itemdescription": "description",
  "timestamp": "timestamp",
  "date": "timestamp",
  "transactiondate": "timestamp",
  "remarks": "remarks",
  "notes": "remarks",
  "comment": "remarks",
};

/**
 * Generate and download sample Excel template with guidelines & valid master references
 */
export function downloadInventorySampleExcel(departments = [], masterItems = []) {
  const sampleRows = [
    {
      "Slip No. (Optional)": "SLIP-2026-001",
      "Type * (Required: ISSUE / RECEIPT / REVERSE)": "ISSUE",
      "From Dept * (Required)": "Stores",
      "To Dept (Optional)": "Production",
      "Item Code * (Required)": "MAT-001",
      "Description (Optional)": "Steel Sheet",
      "Category (Optional)": "Raw Material - Prime Steel",
      "Quantity * (Required > 0)": 50,
      "Timestamp (Optional)": "15-Aug-2026",
      "Remarks (Optional)": "Issued for Line 1 Fabrication",
    },
    {
      "Slip No. (Optional)": "SLIP-2026-002",
      "Type * (Required: ISSUE / RECEIPT / REVERSE)": "RECEIPT",
      "From Dept * (Required)": "Stores",
      "To Dept (Optional)": "Main Store",
      "Item Code * (Required)": "MAT-002",
      "Description (Optional)": "Stainless Steel Rod",
      "Category (Optional)": "Raw Material - Stainless Rod 304",
      "Quantity * (Required > 0)": 100,
      "Timestamp (Optional)": "15-Aug-2026",
      "Remarks (Optional)": "Vendor GRN inward consignment",
    },
    {
      "Slip No. (Optional)": "SLIP-2026-003",
      "Type * (Required: ISSUE / RECEIPT / REVERSE)": "ISSUE",
      "From Dept * (Required)": "Stores",
      "To Dept (Optional)": "Maintenance",
      "Item Code * (Required)": "MAT-003",
      "Description (Optional)": "Bearing 6205",
      "Category (Optional)": "Spare Parts - Deep Groove Bearing",
      "Quantity * (Required > 0)": 5,
      "Timestamp (Optional)": "15-Aug-2026",
      "Remarks (Optional)": "Replaced for Pump Motor 02",
    },
  ];

  const guidelinesData = [
    { "Field Name": "Type", "Required": "REQUIRED *", "Allowed Values & Notes": "Must be ISSUE, RECEIPT, or REVERSE" },
    { "Field Name": "From Dept", "Required": "REQUIRED *", "Allowed Values & Notes": "Must match a valid department (e.g. Stores, Production, Maintenance, Quality Control, Administration)" },
    { "Field Name": "To Dept", "Required": "OPTIONAL", "Allowed Values & Notes": "Destination department name if applicable (e.g. Production)" },
    { "Field Name": "Item Code", "Required": "REQUIRED *", "Allowed Values & Notes": "Must match an existing Item Code in Material Master (e.g. MAT-001 to MAT-005)" },
    { "Field Name": "Quantity", "Required": "REQUIRED *", "Allowed Values & Notes": "Positive number greater than 0 (e.g. 50, 10.5)" },
    { "Field Name": "Category", "Required": "OPTIONAL", "Allowed Values & Notes": "Item Category (auto-filled from Material Master if left blank)" },
    { "Field Name": "Slip No.", "Required": "OPTIONAL", "Allowed Values & Notes": "Optional custom slip number or reference code" },
    { "Field Name": "Description", "Required": "OPTIONAL", "Allowed Values & Notes": "Item description (auto-derived from master if left blank)" },
    { "Field Name": "Timestamp", "Required": "OPTIONAL", "Allowed Values & Notes": "Date of transaction (defaults to current system date if empty)" },
    { "Field Name": "Remarks", "Required": "OPTIONAL", "Allowed Values & Notes": "Optional transaction notes or remarks" },
  ];

  const validReferenceData = masterItems.length > 0
    ? masterItems.map((m) => ({
        "Valid Item Code": m.code,
        "Item Description": m.description,
        "Category": m.category,
        "Unit (UOM)": m.unitOfMeasurement,
        "Store Name": m.storeName,
        "Current Available Balance": m.currentBalance || m.openingBalance || 0,
      }))
    : [
        { "Valid Item Code": "MAT-001", "Item Description": "Steel Sheet", "Category": "Raw Material", "Unit (UOM)": "KG", "Store Name": "Main Store", "Current Available Balance": 5000 },
        { "Valid Item Code": "MAT-002", "Item Description": "Stainless Steel Rod", "Category": "Raw Material", "Unit (UOM)": "KG", "Store Name": "Main Store", "Current Available Balance": 2500 },
        { "Valid Item Code": "MAT-003", "Item Description": "Bearing 6205", "Category": "Spare Parts", "Unit (UOM)": "PCS", "Store Name": "Maintenance Store", "Current Available Balance": 150 },
        { "Valid Item Code": "MAT-004", "Item Description": "Lubricating Oil", "Category": "Consumables", "Unit (UOM)": "LTR", "Store Name": "Maintenance Store", "Current Available Balance": 500 },
        { "Valid Item Code": "MAT-005", "Item Description": "Welding Electrode", "Category": "Consumables", "Unit (UOM)": "KG", "Store Name": "Production Store", "Current Available Balance": 300 },
      ];

  const validDeptData = departments.length > 0
    ? departments.map((d) => ({ "Valid Department Name": d.name, "Department ID": d.id }))
    : [
        { "Valid Department Name": "Stores", "Department ID": 4 },
        { "Valid Department Name": "Production", "Department ID": 1 },
        { "Valid Department Name": "Maintenance", "Department ID": 2 },
        { "Valid Department Name": "Quality Control", "Department ID": 3 },
        { "Valid Department Name": "Administration", "Department ID": 5 },
      ];

  const workbook = XLSX.utils.book_new();

  // Sheet 1: Template Data
  const worksheet1 = XLSX.utils.json_to_sheet(sampleRows);
  const colWidths1 = Object.keys(sampleRows[0]).map((key) => ({
    wch: Math.max(key.length + 3, 16),
  }));
  worksheet1["!cols"] = colWidths1;
  XLSX.utils.book_append_sheet(workbook, worksheet1, "Transactions Template");

  // Sheet 2: Guidelines
  const worksheet2 = XLSX.utils.json_to_sheet(guidelinesData);
  worksheet2["!cols"] = [{ wch: 20 }, { wch: 18 }, { wch: 70 }];
  XLSX.utils.book_append_sheet(workbook, worksheet2, "Field Guidelines");

  // Sheet 3: Available Item Masters Reference
  const worksheet3 = XLSX.utils.json_to_sheet(validReferenceData);
  worksheet3["!cols"] = [{ wch: 18 }, { wch: 25 }, { wch: 20 }, { wch: 14 }, { wch: 20 }, { wch: 25 }];
  XLSX.utils.book_append_sheet(workbook, worksheet3, "Valid Master Items");

  // Sheet 4: Available Departments Reference
  const worksheet4 = XLSX.utils.json_to_sheet(validDeptData);
  worksheet4["!cols"] = [{ wch: 25 }, { wch: 18 }];
  XLSX.utils.book_append_sheet(workbook, worksheet4, "Valid Departments");

  XLSX.writeFile(workbook, "Inventory_Transaction_Upload_Template.xlsx");
}

/**
 * Parse Excel / CSV file, validate required headers & rows against master items, departments, and balances
 */
export function parseAndValidateInventoryExcel(file, { departments = [], masterItems = [], getDeptBalance = () => 0 }) {
  return new Promise((resolve) => {
    const reader = new FileReader();

    reader.onload = (e) => {
      try {
        const data = new Uint8Array(e.target.result);
        const workbook = XLSX.read(data, { type: "array" });

        if (!workbook.SheetNames || workbook.SheetNames.length === 0) {
          return resolve({ valid: false, errors: ["Excel file contains no sheets."], records: [] });
        }

        // Intelligently select the sheet containing transaction data (or fallback to first sheet)
        const targetSheetName =
          workbook.SheetNames.find((n) => /trans|template|entry|sheet1|data/i.test(n)) ||
          workbook.SheetNames[0];

        const worksheet = workbook.Sheets[targetSheetName];
        const rawJson = XLSX.utils.sheet_to_json(worksheet, { header: 1, defval: "" });

        if (rawJson.length === 0) {
          return resolve({ valid: false, errors: ["Excel sheet is completely empty."], records: [] });
        }

        // Header row (Row 1)
        const headerRow = rawJson[0].map((h) => String(h).trim());
        const fieldMapping = {}; // colIndex -> canonical key

        headerRow.forEach((colName, idx) => {
          const normH = normalizeHeader(colName);
          if (HEADER_MAP[normH]) {
            fieldMapping[idx] = HEADER_MAP[normH];
          }
        });

        // Verify all REQUIRED columns are present in the Excel header
        const mappedKeys = new Set(Object.values(fieldMapping));
        const missingRequiredColumns = [];
        REQUIRED_HEADERS.forEach((reqKey) => {
          if (!mappedKeys.has(reqKey)) {
            const config = INVENTORY_EXCEL_FIELDS.find((f) => f.key === reqKey);
            missingRequiredColumns.push(config ? config.label : reqKey);
          }
        });

        if (missingRequiredColumns.length > 0) {
          return resolve({
            valid: false,
            errors: [
              `Missing required column(s) in Excel header: ${missingRequiredColumns.join(", ")}. Please ensure columns for 'Type', 'From Dept', 'Item Code', and 'Quantity' exist.`,
            ],
            records: [],
          });
        }

        const dataRows = rawJson.slice(1);
        if (dataRows.length === 0) {
          return resolve({ valid: false, errors: ["Excel sheet has headers but no transaction rows."], records: [] });
        }

        // Fallback lookup maps for departments and master items if lists are loading
        const effectiveDepts = departments.length > 0 ? departments : [
          { id: 4, name: "Stores" },
          { id: 1, name: "Production" },
          { id: 2, name: "Maintenance" },
          { id: 3, name: "Quality Control" },
          { id: 5, name: "Administration" }
        ];

        const effectiveMasters = masterItems.length > 0 ? masterItems : [
          { id: 1, code: "MAT-001", description: "Steel Sheet", category: "Raw Material", unitOfMeasurement: "KG", currentBalance: 5000 },
          { id: 2, code: "MAT-002", description: "Stainless Steel Rod", category: "Raw Material", unitOfMeasurement: "KG", currentBalance: 2500 },
          { id: 3, code: "MAT-003", description: "Bearing 6205", category: "Spare Parts", unitOfMeasurement: "PCS", currentBalance: 150 },
          { id: 4, code: "MAT-004", description: "Lubricating Oil", category: "Consumables", unitOfMeasurement: "LTR", currentBalance: 500 },
          { id: 5, code: "MAT-005", description: "Welding Electrode", category: "Consumables", unitOfMeasurement: "KG", currentBalance: 300 }
        ];

        const deptMap = {};
        effectiveDepts.forEach((d) => {
          deptMap[d.name.trim().toLowerCase()] = d;
          deptMap[String(d.id)] = d;
        });

        const masterMap = {};
        effectiveMasters.forEach((m) => {
          masterMap[m.code.trim().toUpperCase()] = m;
          masterMap[String(m.id)] = m;
        });

        const parsedRecords = [];
        const errors = [];

        // Validate each data row
        dataRows.forEach((row, rowIdx) => {
          const rowNumber = rowIdx + 2; // Data starts at Row 2

          // Check if row is completely blank
          const isBlankRow = row.every((cell) => cell === null || cell === undefined || String(cell).trim() === "");
          if (isBlankRow) return;

          const rec = {
            rowNumber,
            slipNumber: "",
            type: "ISSUE",
            fromDept: "",
            toDept: "",
            itemCode: "",
            description: "",
            category: "",
            quantity: "",
            timestamp: "",
            remarks: "",
          };

          // Populate mapped cells
          Object.keys(fieldMapping).forEach((colIdx) => {
            const key = fieldMapping[colIdx];
            const cellVal = row[colIdx];
            rec[key] = cellVal !== null && cellVal !== undefined ? String(cellVal).trim() : "";
          });

          const rowErrors = [];

          // 1. Validate Transaction Type
          const upperType = (rec.type || "").toUpperCase().trim();
          if (!upperType) {
            rowErrors.push("Transaction Type is required (ISSUE, RECEIPT, or REVERSE)");
          } else if (!["ISSUE", "RECEIPT", "REVERSE"].includes(upperType)) {
            rowErrors.push(`Invalid Transaction Type '${rec.type}'. Must be ISSUE, RECEIPT, or REVERSE`);
          } else {
            rec.type = upperType;
          }

          // 2. Validate From Department
          if (!rec.fromDept) {
            rowErrors.push("From Dept is required");
          } else {
            const cleanFromDept = rec.fromDept.toLowerCase().trim();
            const matchedFromDept = deptMap[cleanFromDept];
            if (!matchedFromDept) {
              rowErrors.push(`From Dept '${rec.fromDept}' not found in departments list`);
            } else {
              rec.fromDepartmentId = matchedFromDept.id;
              rec.fromDepartmentName = matchedFromDept.name;
            }
          }

          // 3. Validate To Department (optional)
          if (rec.toDept && rec.toDept.trim()) {
            const cleanToDept = rec.toDept.toLowerCase().trim();
            const matchedToDept = deptMap[cleanToDept];
            if (!matchedToDept) {
              rowErrors.push(`To Dept '${rec.toDept}' not found in departments list`);
            } else {
              rec.toDepartmentId = matchedToDept.id;
              rec.toDepartmentName = matchedToDept.name;
            }
          } else {
            rec.toDepartmentId = null;
            rec.toDepartmentName = "";
          }

          // 4. Validate Item Code
          let matchedMaster = null;
          if (!rec.itemCode) {
            rowErrors.push("Item Code is required");
          } else {
            const cleanCode = rec.itemCode.toUpperCase().trim();
            matchedMaster = masterMap[cleanCode];
            if (!matchedMaster) {
              rowErrors.push(`Item Code '${rec.itemCode}' not found in Material Master`);
            } else {
              rec.masterId = matchedMaster.id;
              rec.masterCode = matchedMaster.code;
              rec.masterDescription = matchedMaster.description;
              rec.unitOfMeasurement = matchedMaster.unitOfMeasurement;
              if (!rec.description) rec.description = matchedMaster.description;
              if (!rec.category) rec.category = matchedMaster.category || "General";
            }
          }

          // 5. Populate Category
          if (!rec.category && matchedMaster) {
            rec.category = matchedMaster.category || "General";
          }

          // 6. Validate Quantity
          const numQty = Number(rec.quantity);
          if (!rec.quantity || isNaN(numQty) || numQty <= 0) {
            rowErrors.push(`Invalid Quantity '${rec.quantity}' (must be a positive number greater than 0)`);
          } else {
            rec.quantity = numQty;
          }

          // 7. Stock Balance Check for ISSUE transactions
          if (rec.type === "ISSUE" && matchedMaster && rec.fromDepartmentId && !isNaN(numQty) && numQty > 0) {
            const currentDeptBalance = Number(getDeptBalance(matchedMaster.id, rec.fromDepartmentId)) || 0;
            // Only alert if balance tracking is loaded and balance is strictly 0 or less than quantity
            if (currentDeptBalance > 0 && numQty > currentDeptBalance) {
              rowErrors.push(
                `Insufficient stock for '${matchedMaster.code}' in ${rec.fromDepartmentName}: requested ${numQty}, available closing balance is ${currentDeptBalance}`
              );
            }
          }

          if (rowErrors.length > 0) {
            errors.push(`Row ${rowNumber}: ${rowErrors.join(" | ")}`);
            rec._errors = rowErrors;
          } else {
            rec._errors = [];
          }

          parsedRecords.push(rec);
        });

        if (errors.length > 0) {
          return resolve({
            valid: false,
            errors,
            records: parsedRecords,
            validCount: parsedRecords.filter((r) => r._errors.length === 0).length,
            errorCount: errors.length,
          });
        }

        resolve({
          valid: true,
          errors: [],
          records: parsedRecords,
          validCount: parsedRecords.length,
          errorCount: 0,
        });
      } catch (err) {
        resolve({ valid: false, errors: [`Failed to parse Excel file: ${err.message}`], records: [] });
      }
    };

    reader.onerror = () => {
      resolve({ valid: false, errors: ["Failed to read file from disk."], records: [] });
    };

    reader.readAsArrayBuffer(file);
  });
}

/**
 * Export array of transactions to an .xlsx file download
 */
export function exportTransactionsToExcel(transactionsList = [], filename = "Inventory_Transactions_History.xlsx") {
  if (!transactionsList || transactionsList.length === 0) return;

  const formattedRows = transactionsList.map((tx) => ({
    "Transaction No.": tx.transactionNumber || tx.slipNumber || "-",
    "Slip No.": tx.slipNumber || "-",
    "Type": tx.transactionType || "-",
    "From Dept": tx.fromDepartmentName || "-",
    "To Dept": tx.toDepartmentName || "-",
    "Item Code": tx.masterCode || "-",
    "Description": tx.masterDescription || "-",
    "Category": tx.category || "-",
    "Quantity": tx.quantity || 0,
    "Timestamp": tx.transactionDate ? new Date(tx.transactionDate).toLocaleString("en-IN") : "-",
    "Remarks": tx.remarks || "",
  }));

  const worksheet = XLSX.utils.json_to_sheet(formattedRows);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Transaction History");

  const colWidths = Object.keys(formattedRows[0]).map((key) => ({
    wch: Math.max(key.length + 3, 16),
  }));
  worksheet["!cols"] = colWidths;

  XLSX.writeFile(workbook, filename);
}
