import * as XLSX from "xlsx";

// Canonical field keys for inventory transactions
export const INVENTORY_EXCEL_FIELDS = [
  { key: "slipNumber", label: "Slip No.", required: false, desc: "Optional manual slip reference" },
  { key: "type", label: "Type", required: true, desc: "Must match an operation_master name (case-insensitive)" },
  { key: "fromDept", label: "From Dept", required: true, desc: "Must match a department name (case-insensitive)" },
  { key: "toDept", label: "To Dept", required: true, desc: "Must match a department name (case-insensitive)" },
  { key: "itemCode", label: "Item Code", required: true, desc: "Must exist in item / material master (matched as uppercase)" },
  { key: "description", label: "Description", required: false, desc: "If empty, taken from the item master" },
  { key: "category", label: "Category", required: true, desc: "Must match a category_master name (case-insensitive)" },
  { key: "quantity", label: "Quantity", required: true, desc: "Required numeric quantity greater than 0" },
  { key: "timestamp", label: "Timestamp", required: false, desc: "Optional date/time (defaults to now)" },
  { key: "remarks", label: "Remarks", required: false, desc: "Optional notes" },
];

// Core mandatory columns in Excel header
const REQUIRED_HEADERS = ["type", "fromDept", "toDept", "itemCode", "quantity", "category"];

// Normalize header text for flexible matching:
// 1. Removes text in parentheses (e.g. "(Required: ISSUE / RECEIPT / REVERSE)", "(Optional)")
// 2. Removes asterisks, punctuation, spaces, and lowers case
function normalizeHeader(h) {
  return String(h || "")
    .replace(/\([^)]*\)/g, "") // Strip anything inside parentheses
    .replace(/required|optional|auto-generated|autogenerated/gi, "")
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "");
}

const HEADER_MAP = {
  "type": "type",
  "transactiontype": "type",
  "typeoftransaction": "type",
  "fromdept": "fromDept",
  "fromdepartment": "fromDept",
  "source": "fromDept",
  "sourcedept": "fromDept",
  "todept": "toDept",
  "todepartment": "toDept",
  "destination": "toDept",
  "destdept": "toDept",
  "itemcode": "itemCode",
  "item": "itemCode",
  "code": "itemCode",
  "materialcode": "itemCode",
  "category": "category",
  "categoryofitem": "category",
  "itemcategory": "category",
  "quantity": "quantity",
  "qty": "quantity",
  "amount": "quantity",
  "slipno": "slipNumber",
  "slipnumber": "slipNumber",
  "slip": "slipNumber",
  "manualslipno": "slipNumber",
  "description": "description",
  "itemdescription": "description",
  "timestamp": "timestamp",
  "date": "timestamp",
  "transactiondate": "timestamp",
  "remarks": "remarks",
  "notes": "remarks",
  "comment": "remarks",
};

/**
 * Generate and download sample Excel template with guidelines & valid master references
 */
export function downloadInventorySampleExcel(departments = [], masterItems = [], transactionTypes = [], categories = []) {
  const opName = (t) => t?.type || t?.operationName || "";
  const catName = (c) => c?.categoryName || c?.name || "";
  const firstOp = opName(transactionTypes[0]) || "Material Transfer";
  const inboundOp = transactionTypes.map(opName).find((n) => n.toLowerCase() === "customer rejection receipt") || firstOp;
  const deptA = departments[0]?.name || "";
  const deptB = departments[1]?.name || departments[0]?.name || "";
  const itemA = masterItems[0];
  const itemB = masterItems[1] || masterItems[0];
  const itemC = masterItems[2] || masterItems[0];
  const catA = catName(categories[0]) || itemA?.category || "";
  const catB = catName(categories[1]) || catName(categories[0]) || itemB?.category || "";
  const catC = catName(categories[2]) || catName(categories[0]) || itemC?.category || "";

  const sampleRows = [
    {
      "Slip No. (Optional)": "SLIP-2026-001",
      "Type * (Required)": firstOp,
      "From Dept * (Required)": deptA,
      "To Dept * (Required)": deptB,
      "Item Code * (Required)": itemA?.code || "",
      "Description (Optional)": itemA?.description || "",
      "Category * (Required)": catA,
      "Quantity * (Required > 0)": 50,
      "Timestamp (Optional)": "15-Aug-2026",
      "Remarks (Optional)": "Sample transfer",
    },
    {
      "Slip No. (Optional)": "SLIP-2026-002",
      "Type * (Required)": inboundOp,
      "From Dept * (Required)": deptA,
      "To Dept * (Required)": deptA,
      "Item Code * (Required)": itemB?.code || "",
      "Description (Optional)": itemB?.description || "",
      "Category * (Required)": catB,
      "Quantity * (Required > 0)": 100,
      "Timestamp (Optional)": "15-Aug-2026",
      "Remarks (Optional)": "Sample inbound (Customer Rejection Receipt — stock check skipped)",
    },
    {
      "Slip No. (Optional)": "SLIP-2026-003",
      "Type * (Required)": firstOp,
      "From Dept * (Required)": deptA,
      "To Dept * (Required)": deptB,
      "Item Code * (Required)": itemC?.code || "",
      "Description (Optional)": itemC?.description || "",
      "Category * (Required)": catC,
      "Quantity * (Required > 0)": 5,
      "Timestamp (Optional)": "15-Aug-2026",
      "Remarks (Optional)": "Sample movement",
    },
  ];

  const allowedOps = transactionTypes.map(opName).filter(Boolean).join(", ") || "(load operations from backend)";
  const allowedDepts = departments.map((d) => d.name).filter(Boolean).join(", ") || "(load departments from backend)";
  const allowedCats = categories.map(catName).filter(Boolean).join(", ") || "(load categories from backend)";
  const guidelinesData = [
    { "Field Name": "Type", "Required": "REQUIRED *", "Allowed Values & Notes": `Must match an operation_master name (case-insensitive). Current list: ${allowedOps}` },
    { "Field Name": "From Dept", "Required": "REQUIRED *", "Allowed Values & Notes": `Must match a department name from the backend list (case-insensitive). Current list: ${allowedDepts}` },
    { "Field Name": "To Dept", "Required": "REQUIRED *", "Allowed Values & Notes": `Must match a department name from the backend list (case-insensitive). Current list: ${allowedDepts}` },
    { "Field Name": "Item Code", "Required": "REQUIRED *", "Allowed Values & Notes": "Must exist in item / material master. Matched case-insensitively and compared as uppercase. See Valid Master Items sheet." },
    { "Field Name": "Quantity", "Required": "REQUIRED *", "Allowed Values & Notes": "Required numeric value greater than 0. For types other than Customer Rejection Receipt: if From Dept has a known closing balance > 0, quantity cannot exceed that balance." },
    { "Field Name": "Category", "Required": "REQUIRED *", "Allowed Values & Notes": `Must match a category_master name (case-insensitive). Current list: ${allowedCats}` },
    { "Field Name": "Slip No.", "Required": "OPTIONAL", "Allowed Values & Notes": "Optional custom slip number or reference code" },
    { "Field Name": "Description", "Required": "OPTIONAL", "Allowed Values & Notes": "If empty, taken from the item master" },
    { "Field Name": "Timestamp", "Required": "OPTIONAL", "Allowed Values & Notes": "Date of transaction (defaults to current system date if empty)" },
    { "Field Name": "Remarks", "Required": "OPTIONAL", "Allowed Values & Notes": "Optional transaction notes or remarks" },
  ];

  const validReferenceData = masterItems.map((m) => ({
        "Valid Item Code": m.code,
        "Item Description": m.description,
        "Category": m.category,
        "Unit (UOM)": m.unitOfMeasurement,
        "Store Name": m.storeName,
        "Current Available Balance": m.currentBalance || m.openingBalance || 0,
      }));

  const validDeptData = departments.map((d) => ({ "Valid Department Name": d.name, "Department ID": d.id }));

  const validOpData = transactionTypes.map((t) => ({
    "Valid Operation": t.type || t.operationName,
    "Operation ID": t.id,
  }));

  const validCatData = categories.map((c) => ({
    "Valid Category": catName(c),
    "Category ID": c.id,
  }));

  const workbook = XLSX.utils.book_new();

  // Sheet 1: Template Data
  const worksheet1 = XLSX.utils.json_to_sheet(sampleRows);
  const colWidths1 = Object.keys(sampleRows[0]).map((key) => ({
    wch: Math.max(key.length + 3, 16),
  }));
  worksheet1["!cols"] = colWidths1;
  XLSX.utils.book_append_sheet(workbook, worksheet1, "Transactions Template");

  // Sheet 2: Guidelines
  const worksheet2 = XLSX.utils.json_to_sheet(guidelinesData);
  worksheet2["!cols"] = [{ wch: 20 }, { wch: 18 }, { wch: 70 }];
  XLSX.utils.book_append_sheet(workbook, worksheet2, "Field Guidelines");

  // Sheet 3: Available Item Masters Reference
  const worksheet3 = XLSX.utils.json_to_sheet(validReferenceData.length ? validReferenceData : [{ "Valid Item Code": "(none loaded from backend)" }]);
  worksheet3["!cols"] = [{ wch: 18 }, { wch: 25 }, { wch: 20 }, { wch: 14 }, { wch: 20 }, { wch: 25 }];
  XLSX.utils.book_append_sheet(workbook, worksheet3, "Valid Master Items");

  // Sheet 4: Available Departments Reference
  const worksheet4 = XLSX.utils.json_to_sheet(validDeptData.length ? validDeptData : [{ "Valid Department Name": "(none loaded from backend)" }]);
  worksheet4["!cols"] = [{ wch: 25 }, { wch: 18 }];
  XLSX.utils.book_append_sheet(workbook, worksheet4, "Valid Departments");

  const worksheet5 = XLSX.utils.json_to_sheet(validOpData.length ? validOpData : [{ "Valid Operation": "(none loaded from operation_master)" }]);
  worksheet5["!cols"] = [{ wch: 40 }, { wch: 18 }];
  XLSX.utils.book_append_sheet(workbook, worksheet5, "Valid Operations");

  const worksheet6 = XLSX.utils.json_to_sheet(validCatData.length ? validCatData : [{ "Valid Category": "(none loaded from category_master)" }]);
  worksheet6["!cols"] = [{ wch: 40 }, { wch: 18 }];
  XLSX.utils.book_append_sheet(workbook, worksheet6, "Valid Categories");

  XLSX.writeFile(workbook, "Inventory_Transaction_Upload_Template.xlsx");
}

/**
 * Parse Excel / CSV file, validate required headers & rows against master items, departments, and balances
 */
export function parseAndValidateInventoryExcel(file, { departments = [], masterItems = [], transactionTypes = [], categories = [], getDeptBalance = () => 0 }) {
  return new Promise((resolve) => {
    const reader = new FileReader();

    reader.onload = (e) => {
      try {
        const data = new Uint8Array(e.target.result);
        const workbook = XLSX.read(data, { type: "array" });

        if (!workbook.SheetNames || workbook.SheetNames.length === 0) {
          return resolve({ valid: false, errors: ["Excel file contains no sheets."], records: [] });
        }

        // Intelligently select the sheet containing transaction data (or fallback to first sheet)
        const targetSheetName =
          workbook.SheetNames.find((n) => /trans|template|entry|sheet1|data/i.test(n)) ||
          workbook.SheetNames[0];

        const worksheet = workbook.Sheets[targetSheetName];
        const rawJson = XLSX.utils.sheet_to_json(worksheet, { header: 1, defval: "" });

        if (rawJson.length === 0) {
          return resolve({ valid: false, errors: ["Excel sheet is completely empty."], records: [] });
        }

        // Header row (Row 1)
        const headerRow = rawJson[0].map((h) => String(h).trim());
        const fieldMapping = {}; // colIndex -> canonical key

        headerRow.forEach((colName, idx) => {
          const normH = normalizeHeader(colName);
          if (HEADER_MAP[normH]) {
            fieldMapping[idx] = HEADER_MAP[normH];
          }
        });

        // Verify all REQUIRED columns are present in the Excel header
        const mappedKeys = new Set(Object.values(fieldMapping));
        const missingRequiredColumns = [];
        REQUIRED_HEADERS.forEach((reqKey) => {
          if (!mappedKeys.has(reqKey)) {
            const config = INVENTORY_EXCEL_FIELDS.find((f) => f.key === reqKey);
            missingRequiredColumns.push(config ? config.label : reqKey);
          }
        });

        if (missingRequiredColumns.length > 0) {
          return resolve({
            valid: false,
            errors: [
              `Missing required column(s) in Excel header: ${missingRequiredColumns.join(", ")}. Please ensure columns for 'Type', 'From Dept', 'To Dept', 'Item Code', 'Quantity', and 'Category' exist.`,
            ],
            records: [],
          });
        }

        const dataRows = rawJson.slice(1);
        if (dataRows.length === 0) {
          return resolve({ valid: false, errors: ["Excel sheet has headers but no transaction rows."], records: [] });
        }

        // Fallback lookup maps for departments and master items if lists are loading
        const allowedTypes = (transactionTypes || [])
          .map((t) => (t.type || t.operationName || "").trim())
          .filter(Boolean);
        const allowedTypeSet = new Set(allowedTypes.map((t) => t.toLowerCase()));

        const allowedCategories = (categories || [])
          .map((c) => (c.categoryName || c.name || "").trim())
          .filter(Boolean);
        const allowedCategorySet = new Set(allowedCategories.map((c) => c.toLowerCase()));

        const effectiveDepts = departments;
        const effectiveMasters = masterItems;

        const deptMap = {};
        effectiveDepts.forEach((d) => {
          deptMap[d.name.trim().toLowerCase()] = d;
          deptMap[String(d.id)] = d;
        });

        const masterMap = {};
        effectiveMasters.forEach((m) => {
          masterMap[m.code.trim().toUpperCase()] = m;
          masterMap[String(m.id)] = m;
        });

        const parsedRecords = [];
        const errors = [];

        // Validate each data row
        dataRows.forEach((row, rowIdx) => {
          const rowNumber = rowIdx + 2; // Data starts at Row 2

          // Check if row is completely blank
          const isBlankRow = row.every((cell) => cell === null || cell === undefined || String(cell).trim() === "");
          if (isBlankRow) return;

          const rec = {
            rowNumber,
            slipNumber: "",
            type: "",
            fromDept: "",
            toDept: "",
            itemCode: "",
            description: "",
            category: "",
            quantity: "",
            timestamp: "",
            remarks: "",
          };

          // Populate mapped cells
          Object.keys(fieldMapping).forEach((colIdx) => {
            const key = fieldMapping[colIdx];
            const cellVal = row[colIdx];
            rec[key] = cellVal !== null && cellVal !== undefined ? String(cellVal).trim() : "";
          });

          const rowErrors = [];

          // 1. Validate Transaction Type / Operation Name
          const rawType = (rec.type || "").trim();
          if (!rawType) {
            rowErrors.push("Transaction Type / Operation Name is required");
          } else if (allowedTypeSet.size > 0 && !allowedTypeSet.has(rawType.toLowerCase())) {
            rowErrors.push(`Type '${rawType}' is not in operation_master`);
          } else {
            const canonical = allowedTypes.find((t) => t.toLowerCase() === rawType.toLowerCase());
            rec.type = canonical || rawType;
          }


          // 2. Validate From Department
          if (!rec.fromDept) {
            rowErrors.push("From Dept is required");
          } else {
            const cleanFromDept = rec.fromDept.toLowerCase().trim();
            const matchedFromDept = deptMap[cleanFromDept];
            if (!matchedFromDept) {
              rowErrors.push(`From Dept '${rec.fromDept}' not found in departments list`);
            } else {
              rec.fromDepartmentId = matchedFromDept.id;
              rec.fromDepartmentName = matchedFromDept.name;
            }
          }

          // 3. Validate To Department (required)
          if (!rec.toDept) {
            rowErrors.push("To Dept is required");
            rec.toDepartmentId = null;
            rec.toDepartmentName = "";
          } else {
            const cleanToDept = rec.toDept.toLowerCase().trim();
            const matchedToDept = deptMap[cleanToDept];
            if (!matchedToDept) {
              rowErrors.push(`To Dept '${rec.toDept}' not found in departments list`);
            } else {
              rec.toDepartmentId = matchedToDept.id;
              rec.toDepartmentName = matchedToDept.name;
            }
          }

          // 4. Validate Item Code
          let matchedMaster = null;
          if (!rec.itemCode) {
            rowErrors.push("Item Code is required");
          } else {
            const cleanCode = rec.itemCode.toUpperCase().trim();
            matchedMaster = masterMap[cleanCode];
            if (!matchedMaster) {
              rowErrors.push(`Item Code '${rec.itemCode}' not found in Material Master`);
            } else {
              rec.masterId = matchedMaster.id;
              rec.masterCode = matchedMaster.code;
              rec.masterDescription = matchedMaster.description;
              rec.unitOfMeasurement = matchedMaster.unitOfMeasurement;
              if (!rec.description) rec.description = matchedMaster.description;
            }
          }

          // 5. Validate Category (required — must match category_master)
          if (!rec.category) {
            rowErrors.push("Category is required");
          } else if (allowedCategorySet.size > 0 && !allowedCategorySet.has(rec.category.toLowerCase())) {
            rowErrors.push(`Category '${rec.category}' is not in category_master`);
          } else {
            const canonicalCat = allowedCategories.find((c) => c.toLowerCase() === rec.category.toLowerCase());
            rec.category = canonicalCat || rec.category;
          }

          // 6. Validate Quantity
          const numQty = Number(rec.quantity);
          if (!rec.quantity || isNaN(numQty) || numQty <= 0) {
            rowErrors.push(`Invalid Quantity '${rec.quantity}' (must be a positive number greater than 0)`);
          } else {
            rec.quantity = numQty;
          }

          // 7. Stock balance check for non-inbound operations
          if (rec.type && rec.type.toLowerCase() !== "customer rejection receipt" && matchedMaster && rec.fromDepartmentId && !isNaN(numQty) && numQty > 0) {
            const currentDeptBalance = Number(getDeptBalance(matchedMaster.id, rec.fromDepartmentId, rec.category)) || 0;
            // Only alert if balance tracking is loaded and balance is strictly 0 or less than quantity
            if (currentDeptBalance > 0 && numQty > currentDeptBalance) {
              rowErrors.push(
                `Insufficient stock for '${matchedMaster.code}' in ${rec.fromDepartmentName}: requested ${numQty}, available closing balance is ${currentDeptBalance}`
              );
            }
          }

          if (rowErrors.length > 0) {
            errors.push(`Row ${rowNumber}: ${rowErrors.join(" | ")}`);
            rec._errors = rowErrors;
          } else {
            rec._errors = [];
          }

          parsedRecords.push(rec);
        });

        if (errors.length > 0) {
          return resolve({
            valid: false,
            errors,
            records: parsedRecords,
            validCount: parsedRecords.filter((r) => r._errors.length === 0).length,
            errorCount: errors.length,
          });
        }

        resolve({
          valid: true,
          errors: [],
          records: parsedRecords,
          validCount: parsedRecords.length,
          errorCount: 0,
        });
      } catch (err) {
        resolve({ valid: false, errors: [`Failed to parse Excel file: ${err.message}`], records: [] });
      }
    };

    reader.onerror = () => {
      resolve({ valid: false, errors: ["Failed to read file from disk."], records: [] });
    };

    reader.readAsArrayBuffer(file);
  });
}

/**
 * Export array of transactions to an .xlsx file download
 */
export function exportTransactionsToExcel(transactionsList = [], filename = "Inventory_Transactions_History.xlsx") {
  if (!transactionsList || transactionsList.length === 0) return;

  const formattedRows = transactionsList.map((tx) => ({
    "Transaction No.": tx.transactionNumber || tx.slipNumber || "-",
    "Slip No.": tx.slipNumber || "-",
    "Type": tx.transactionType || "-",
    "From Dept": tx.fromDepartmentName || "-",
    "To Dept": tx.toDepartmentName || "-",
    "Item Code": tx.masterCode || "-",
    "Description": tx.masterDescription || "-",
    "Category": tx.category || "-",
    "Quantity": tx.quantity || 0,
    "Timestamp": tx.transactionDate ? new Date(tx.transactionDate).toLocaleString("en-IN") : "-",
    "Remarks": tx.remarks || "",
  }));

  const worksheet = XLSX.utils.json_to_sheet(formattedRows);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Transaction History");

  const colWidths = Object.keys(formattedRows[0]).map((key) => ({
    wch: Math.max(key.length + 3, 16),
  }));
  worksheet["!cols"] = colWidths;

  XLSX.writeFile(workbook, filename);
}
