-- Real Customer Master Data from user sheet
TRUNCATE TABLE public.customer_master RESTART IDENTITY;
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-001', 'CUST-001', 'Ashok Leyland', 'COMP-001', 'DOMESTIC', '06AARCS3816N1ZQ', 'AARCS3816N', 'Ashok Ley', 'Deependra.Choubey@ashokleyland.com,Jayakumar@ashokleyland.com,Chhatrpal.Singh@ashokleyland.com,Vikramsingh.R@ashokleyland.com,Nagarajan.A2@ashokleyland.com, POTHIRAJ.P2@ashokleyland.com', '', 'Silver Muller Rubber Ltd.(Sales) PHASE-III, PLOT NO.443, EPIP HSIIDC, KUNDLI, Sonipat, Haryana, 131028', '', 'Haryana', '06', 'REGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-002', 'CUST-002', 'Bir Auto And Tractor Agencies', 'COMP-001', 'OEM', '07AAAPM6656Q1Z2', 'AAAPM6656Q', 'Bir Auto', '', '', 'GROUND FLOOR, 2935, HAMILTON ROAD,, KASHMERE GATE, New Delhi, Delhi, 110006', 'India', 'Delhi', '07', 'REGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-003', 'CUST-003', 'Dana India Private Ltd-PUNE', 'COMP-001', 'DOMESTIC', '27AABCD1873A1Z3', 'AABCD1873A', 'Prabhakaran : HCV', 'd.prabakaran@alsn.com, ratnesh.chourasiya@alsn.com, dadasaheb.thorat@alsn.com', '73390 00868, 95525 10464', 'Plot Number 01 Gat Number 51/1-3, 52-54, 56-59,, Global Industrial Park, Post-Vasuli, Taluka Khed,, Bhamboli, Pune, Maharashtra, 410501', '', 'Maharashtra', '27', 'REGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-004', 'CUST-004', 'Diesel Technic (M.E) Fze - Dubai', 'COMP-001', 'EXPORT', '', '', 'DT-Dubai', '', '971 48120 100', 'Silver Muller Rubber Ltd.(Sales) PHASE-III, PLOT NO.443, EPIP HSIIDC, KUNDLI, Sonipat, Haryana, 131028', '', '', '', 'UNREGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-005', 'CUST-005', 'Diesel Technic Se Germany', 'COMP-001', 'EXPORT', '', '', 'Ina Johannes
Jessica Wiegmann : Packing Mgr', 'lea.harzmeier@dieseltechnic.com,j.wiegmann@dieseltechnic.com,Johannes@dieseltechnic.com,dannemann@dieseltechnic.com,, dannemann@dieseltechnic.com\,laeticia.kowitz@dieseltechnic.com,laeticia.kowitz@dieseltechnic.com>,j.rehling@dieseltechnic.com', '', 'Silver Muller Rubber Ltd.(Sales) PHASE-III, PLOT NO.443, EPIP HSIIDC, KUNDLI, Sonipat, Haryana, 131028', '', '', '', 'UNREGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-006', 'CUST-006', 'Elpi General Trading Llc', 'COMP-001', 'EXPORT', '', '', 'ELPI', 'info@elpi.com', '', 'S-5, BEHIND KARACHI DARBAR RESTAURANT, AL MAKTOUM HOSPITAL ROAD, DEIRA, DUBAI, U.A.E', '', '', '', 'UNREGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-007', 'CUST-007', 'Europart Middle East Fzco', 'COMP-001', 'EXPORT', '', '', 'Vitaly
Shahzad Riaz - Purchase Exe', '1243@europart.ru, R.Shahzad@europart.net, H.Charawanan@europart.net', '9714-8808449, , 04 8808449, 971 55 956 9488', 'Plot # M209 Street # N400 , JAFZA North, Jebel Ali Free Zone , Dubai, United Arab Emirates, Ph:-04 8808449 Fax-04 8808525, MOBILE+971 55 956 9488', 'Jebel Ali Free Zone , Dubai', '', '', 'UNREGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-008', 'CUST-008', 'J.K. Fenner India Limited(Gurugram)', 'COMP-001', 'OEM', '06AAACJ7230N2ZF', 'AAACJ7230N', 'Avinash Kumar :Deputy Manager', 'prashant.b@jkfenner.com, avinashkumar.p@jkfenner.com', '8586865307', 'C/O SEABIRD LOGISOLUTION LTD, NO.19., VILL-DABODHA,KHASRA NO.4/18,22,23,24,5//11,6//2,3,4, FARRUKHNAGAR,GURUGRAM,HARYANA-122506', '', 'Haryana', '06', 'REGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-009', 'CUST-009', 'J.K. FENNER (INDIA) LTD (CHENNAI)', 'COMP-001', 'DOMESTIC', '33AAACJ7230N1ZJ', 'AAACJ7230N', 'Lion Kumar

Vikash Panchamani : Supply Chain :91-9003246132

P Vikash: Plant PURCHSE HEAD :+91-9003246132', 'Leonkumar.g@jkfenner.com,sanjeevkumar.shishpal@jkfenner.com, KUTHALAMAGESH.n@jkfenner.com, sasikumarr@jkfenner.com, saravana.kumar1@safexpress.com', '98416 53170, 91761 76114 / 95856 52819', 'J.K-FENNER (INDIA) LTD, F-21 & 22,SIPCOT INDUSTRIAL PARK, SRIPERUMBADUR, KANCHEEPURAM-602 105, TAMIL NADU', 'KANCHEEPURAM', 'Tamil Nadu', '33', 'REGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-010', 'CUST-010', 'Kistenmacher Auto Technik', 'COMP-001', 'EXPORT', '', '', 'KAT', 'katlogistics@kat-germany.de, Pecherska@kat-germany.de, Krause@kat-germany.de, Subramanian@kat-germany.de', '', 'Kohli Auto Traders WZ 76, TODAPUR, NEW DELHI 110012', '', '', '', 'UNREGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-011', 'CUST-011', 'Lakhdatar Shyam Industries Private Limited', 'COMP-001', 'OEM', '09AAICR4269F1Z2', 'AAICR4269F', 'Mr. Shyam', 'Lakhdatarshyaminds@gmail.com', '01147587176, 93122 07176', 'Plot No. F-40/308, Transport Nagar Phase II,, Kanpur Road, Lukhnow, Uttar Pradesh, 226012', '', 'Uttar Pradesh', '09', 'REGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-012', 'CUST-012', 'Llc "F.A.Logistic"', 'COMP-001', 'EXPORT', '', '', 'Sergey Suryadnov
Aleksej,', 'vsyannikov.u@forum-auto.ru,suryadnov.s@forum-auto.ru,sorokin.a@forum-auto.ru,, ovsyannikov.u@forum-auto.ru,viv33in@gmail.com,, suryadnov.s@forum-auto.ru,egorov.da@forum-auto.ru, ovsyannikov.u@forum-auto.ru,, sorokin.a@forum-auto.ru,viv33in@gmail.com, gorlov.o@forum-auto.ru', '-10117', '4,SOLNECHNOGORORSKY PROEZD,125413, MOSCOW,RUSSIA FEDERATION', '', '', '', 'UNREGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-013', 'CUST-013', 'Meritor Hvs (India) Limited', 'COMP-001', 'DOMESTIC', '27AABCM8911G1ZH', 'AABCM8911G', 'Selvan Shrinivasan
Mr. Deva Accounts :8799986216', 'CVA.Pune3@cummins.com,CVA.Pune2@cummins.com,Laxmikant.Somnathe@cummins.com,, Suresh.Joshi@cummins.com,, selvan.shrinivasan@cummins.com, devidas.anbhule@cummins.com, Laxmikant.Somnathe@cummins.com', '91 8799990281', 'CVA Warehouse, Gate No.34, Taluka Maval, Near Talegaon, Pune-412106, Maharashtra', 'PUNE', 'Maharashtra', '27', 'REGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-014', 'CUST-014', 'SAHNI DISTRIBUTORS PVT. LTD./DFT', 'COMP-001', 'OEM', '07AAFCS9276E1Z1', 'AAFCS9276E', 'DFT', '', '', 'KHASRA NO-38, ROAD NO-3, DABRI VILLAGE, West Delhi, Delhi, 110045  "PLOT NO. 313, ROAD NO.3, DABRI INDUSTRIAL AREA, NEW DELHI-110045 (INDIA)"', '', 'Delhi', '07', 'REGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-015', 'CUST-015', 'Sfp Products India Private Limited', 'COMP-001', 'DOMESTIC', '07ABPCS1939M1ZM', 'ABPCS1939M', 'SFP', 'whatsapp', '', 'KOHLI AUTO TRADERS WZ-76, TODAPUR, DELHI, SOUTH WEST DELHI, DELHI-110012', 'NEW DELHI', 'DELHI', '07', 'REGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-016', 'CUST-016', 'Silver Muller Rubber Ltd.(Sales)', 'COMP-001', 'DOMESTIC', '06AARCS3816N1ZQ', 'AARCS3816N', 'Ravi Anand', 'design@silvermuller.com', '', 'PHASE-III, PLOT NO.443, EPIP HSIIDC, KUNDLI, Sonipat, Haryana, 131028', 'KUNDLI', 'Haryana', '06', 'REGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-017', 'CUST-017', 'Steel Impex & Industries', 'COMP-001', 'OEM', '27AAAFS3367A1ZI', 'AAAFS3367A', 'Sunil Batra', 'whatsapp', '-28458087', 'HISSA NO 6, SURVEY NO 115, GHODBUNDER VILLAGE ROAD, MIRA ROAD EAST, THANE, MAHARASHTRA- 401107', '', 'Maharashtra', '27', 'REGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-018', 'CUST-018', 'Kohli Auto Traders', 'COMP-001', 'OEM', '', '', 'Kohli', 'group.silverseal@gmail.com', '', 'WZ 76, TODAPUR, NEW DELHI 110012', '', '', '', 'UNREGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-019', 'CUST-019', 'Y.S.M Spring International', 'COMP-001', 'OEM', '', '', 'YSM', 'whatsapp', '', '96/99, Bhatwara, Shahpeer Gate, Shohrab Gate, Meerut, Uttar Pradesh 250002', '', 'Uttar Pradesh', '', 'UNREGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-020', 'CUST-020', 'Partap Singh and Sons-GUJRAT', 'COMP-001', 'DOMESTIC', '24AAAFP8679G1ZY', 'AAAFP8679G', 'Sartaj Chadha', 'sartajchadha78@gmail.com', '9892523522', 'UMARWADA, VPUNE KUMBHARIA ROAD, SARDAR COMPLEX, SHOP NO.B-50,ROYAL TOWNSHIP', 'SURAT', 'GUJRAT', '24', 'REGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-021', 'CUST-021', 'Partap Singh and Sons-MUMBAI', 'COMP-001', 'DOMESTIC', '27AAAFP8679G1ZS', 'AAAFP8679G', 'Sartaj Chadha', 'sartajchadha78@gmail.com', '9892523522', 'SHOP NO 5, 29-B, NAVAKAR BLDG SHOP NO 5, KENNEDY BRIDGE, OPERA HOUSE, MUMBAI', 'KALAMBOLI', 'MAHARASHTRA', '27', 'REGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-022', 'CUST-022', 'KJ', 'COMP-001', 'OEM', '', '', 'KJ', '', '', 'PHASE-III, PLOT NO.443, EPIP HSIIDC, KUNDLI, Sonipat, Haryana, 131028', '', 'Haryana', '', 'UNREGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-023', 'CUST-023', 'RSK MOTORS', 'COMP-001', 'DOMESTIC', '27AAMPK9641H1ZA', 'AAMPK9641H', 'RSK MOTORS', 'whatsapp', '', '4-C, PURSHOTTAM BUILDING, TRIBHUVAN ROAD, MUMBAI-400004', 'TRIBHUVAN ROAD', 'MAHARASHTRA', '27', 'REGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-024', 'CUST-024', 'Safety Stock', 'COMP-001', 'OEM', '', '', 'Safety Stock', '', '', '', '', '', '', 'UNREGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-025', 'CUST-025', 'J.K. Fenner India Limited(Export)', 'COMP-001', 'EXPORT', '06AAACJ7230N2ZF', 'AAACJ7230N', 'Avinash Kumar :Deputy Manager', '', '8586865307', 'C/O SEABIRD LOGISOLUTION LTD, NO.19., VILL-DABODHA,KHASRA NO.4/18,22,23,24,5//11,6//2,3,4, FARRUKHNAGAR,GURUGRAM,HARYANA-122506', '', 'Haryana', '06', 'REGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-026', 'CUST-026', 'VEE TEE AUTO MANUFACTURING CO. PVT. LTD.', 'COMP-001', 'OEM', '', '', 'Rajesh Tiwari', 'rajesh@virtechnique.com', '98204 63605', 'PLOT NO. 10, SECTOR 19D, NEAR APMC MARKET, VASHI, NAVI MUMBAI. TEL: 022-67675000 FAX: 022-27835004', '', 'MAHARASHTRA', '', 'UNREGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-027', 'CUST-027', 'SATYAM ENTERPRISES', 'COMP-001', 'DOMESTIC', '07AAFPM5657A1ZV', 'AAFPM5657A', 'Rohit', 'whatsapp', '9811422501', '3520/1 CHUTTANI MANZIL NICHOLSON ROAD MORI GATE DELHI 110006', '', 'Delhi', '07', 'REGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-028', 'CUST-028', 'NBC', 'COMP-001', 'DOMESTIC', '', '', 'Sanjeev Kumar', 'sanjeev.kumar2@nbcbearings.in, manish.sinha@nbcbearings.in, rahul.dewedi@nbcbearings.in', '8860880244', 'National Engineering Industries Ltd. (Auto Adjacencies Division) Khatipura Road, Jaipur - 302006, India .', '', 'RAJASTHAN', '', 'UNREGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-029', 'CUST-029', 'FREUDENBERG-NOK', 'COMP-001', 'DOMESTIC', '06AAFCS0306K1ZL', 'AAFCS0306K', 'FNI', 'Paltu.Sana@corteco.in, ,Mandeep.Sehgal@fst.com, Pankaj.Jariyal@fst.com', '', 'Freudenberg-NOK Pvt.Ltd. C/O Rhenus Contract Logistics I Pvt Ltd. MUF10, Shail Embassy Ind. Park, F+H Block Situated Near SH 15A, 122506 GURGAON, HARYANA, INDIA', '', 'Haryana', '06', 'REGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-030', 'CUST-030', 'TRUCK MOTORS', 'COMP-001', 'EXPORT', '', '', 'TM', 'i.efimov@tmtr.ru, a.utkin@tmtr.ru, a.iakimchenko@tmtr.ru, l.vdovina@tmtr.ru, a.dumbadze@tmtr.ru, e.petrygina@tmtr.ru, i.latfullin@tmtr.ru, a.samylkin@tmtr.ru', '', 'TME SPARE PARTS TRADING DWC-LLC P.O. BOX 644272, DUBAI, UAE, PHONE : +97148879220, truckmotorsdubai@gmail.com', '', '', '', 'UNREGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-031', 'CUST-031', 'NEW KIM AUTO PRODUCTS', 'COMP-001', 'DOMESTIC', '07BDKPB5855J1ZB', 'BDKPB5855J', 'KIM', '', 'Kshitiz Bhaskar', 'PLOT NO 191, GROUND FLOOR, DSIDC PKT M SEC 5, NEAR LABOUR CHOWK SEC 5, Bawana Industrial Area, NEW DELHI, NORTH WEST DELHI, DELHI, 110039', '', 'Delhi', '07', 'REGISTERED', 500000.00, 'ACTIVE');
INSERT INTO public.customer_master (customer_id, customer_code, customer_name, company_id, customer_type, gstin, pan, contact_person, email, phone, address, city, state, state_code, gst_registration_type, credit_limit, status) VALUES ('CUST-032', 'CUST-032', 'TIMKEN GGB TECHNOLOGY PVT LTD', 'COMP-001', 'DOMESTIC', '27AABCE7337G1ZN', 'AABCE7337G', 'TIMKEN', 'd.raghavendra@timken.com, swarup.mandal@timken.com', 'Raghavendra', '6th Floor, Wing B, Unit No B603, S No. 87/1A Plot No.187(Part). Amar Business Zone , Baner Road Pune, 411045 GSTIN/UIN: 27AABCE7337G1ZN State Name : Maharashtra, Code : 27', '', 'MAHARASHTRA', '27', 'REGISTERED', 500000.00, 'ACTIVE');